### ISSUE TITLE
Tiling artifacts exist on 1m DEM roughly every 60m

### ISSUE THREAD

**Issue by brentwilder** [hyriver/py3dep#57]
# **What happened**:  
My team and I used `.get_map()` function (see below) to generate 1 meter DEM for our study site. On first glance the DEM looked perfectly fine. However, when we differenced this grid with our own DEM grid with snow, we found there were edge/tiling artifacts from the 3DEP product. At first I believed this to be our own snow DEM. However, after extensive testing I was able to narrow it down to being from the USGS DEM. Finally, I tried it with 1 meter DEM straight from https://apps.nationalmap.gov/downloader/ , __and there were no artifacts__. Meaning that there were ~60m tiling artifacts present as a result of me misusing py3dep (very possible), or something off in the way py3dep is calling the 1m 3DEP dataset.

```python
def download_dem(las_fp, dem_fp = 'dem.tif'):
    """
    Reads the crs and bounds of a las file and downloads a DEM from py3dep
    Must be in the CONUS.
    Parameters:
    las_fp (str): filepath to las file to get bounds and crs
    dem_fp (str) [optional]: filepath to save DEM at. [default = './dem.tif']
    Returns:
    crs (pyproj CRS): CRS object from las header
    project (shapely transform): shapely transform used in conversion
    """
    # read crs of las file
    with laspy.open(las_fp) as las:
        hdr = las.header
        crs = hdr.parse_crs()
    log.debug(f"CRS used is {crs}")
    # create transform from wgs84 to las crs
    wgs84 = pyproj.CRS('EPSG:4326')
    project = pyproj.Transformer.from_crs(crs, wgs84 , always_xy=True).transform
    # calculate bounds of las file in wgs84
    utm_bounds = box(hdr.mins[0], hdr.mins[1], hdr.maxs[0], hdr.maxs[1])
    wgs84_bounds = transform(project, utm_bounds)
    # download dem inside bounds
    dem_wgs = py3dep.get_map('DEM', wgs84_bounds, resolution = 1, crs = 'epsg:4326')
    log.debug(f"DEM bounds: {dem_wgs.rio.bounds()}. Size: {dem_wgs.size}")
    # reproject to las crs and save
    dem_utm = dem_wgs.rio.reproject(crs)
    dem_utm.rio.to_raster(dem_fp)
    log.debug(f"Saved to {dem_fp}")
    return dem_fp, crs, project

```

# **Environment**:
OS: Ubuntu 20.04.4 LTS x86_64

py3dep version: 0.13.3

Conda environemnt via .yaml below
```yaml
name: iceroad
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - python-pdal
  - gdal
  - rioxarray
  - py3dep
  - shapely
  - docopt
  - pip
  - pip:
    - whitebox
    - matplotlib
    - geopandas
    - rasterio
    - xarray
    - pandas
    - laspy[lazrs,laszip]
```

## Difference of DEMs with py3dep

![bad](https://user-images.githubusercontent.com/56372982/180662232-3a74e357-d114-4c0a-a4da-ba1e3169eadc.png)

## Difference of DEMs with https://apps.nationalmap.gov/downloader/

![clean](https://user-images.githubusercontent.com/56372982/180662234-2b3c9f33-14ad-46f1-a704-c39812d67dde.png)

**Comment by cheginit** [comment]
Thanks for reporting this issue. Did you have this problem only recently and not before? The 3DEP team recently updated their raw data but in the process they introduced some issues to their dynamic tiling. There's an open [issue](https://github.com/hyriver/py3dep/issues/56) related to this. I have already reported the issue to the 3DEP team and they said that they're working on it.

Most probably this issue is related to the dynamic layer of 3DEP and not the static data. The static data is updated more frequently but they might not be seamless and are only available at specific resolutions. The dynamic layer, on the other hand, produces seamless topo data for any region of interest at any resolution based on the best available raw data.

**Comment by brentwilder** [comment]
This is actually my first time using py3dep so I can't say for certain, but this does seem to be similar to the issue you mentioned. Also, thank you for contacting 3DEP team and we look forward to hearing a response back on this.

I guess I'm still confused as to why the USGS National Map Downloader did not have this issue? Does USGS National Map Downloader pull from static layer, and py3dep pull from dynamic layer? Thanks in advance for the clarification.

**Comment by cheginit** [comment]
Right, the downloader gets the DEM data only at specific resolutions (1 m, 5 m, 10 m, 30 m, ...) from static files. However, `py3dep` relies on the [Web Map Service](https://elevation.nationalmap.gov/arcgis/rest/services/3DEPElevation/ImageServer) of the 3DEP. This web service uses raw data at the highest available resolution in the region of interest to compute (by interpolation and resampling) various topo data (DEM, slope, aspect, etc.) at any given resolution (any positive float number).

**Comment by brentwilder** [comment]
Got it, thank you for background! I'll keep my eye on this issue over the next few weeks continue testing for my study area (around Boise, Idaho).

**Comment by cheginit** [comment]
The issue should be fixed now. This is the message that I got from the 3DEP team regarding the issue:

> It seems the service was retaining cached MRF images indefinitely, which prevented corrections to the source data from being propagated into the service display. This resulted in an area of older DEMs with edge artifacts showing, even though the source DEMs had been re-created without these artifacts (thus the clean version from Downloader). We're taking steps to ensure these cached files are flushed regularly, so this doesn't happen again.

Just make sure to remove your cache file (`./cache/aiohttp_cache.sqlite`) so it gets the new data from the service instead of the old data from the cache.

Also, a note about you code snippet. You don't have to reproject your bound to 4326 prior to passing it to `py3dep`. You can pass bounds (or geometry) in any CRS and then just pass its CRS via the `geo_crs` argument of `get_map`. Under-the-hood, this function reprojects the input geometry from `geo_crs` (CRS of the input geometry) to `crs` (the target service CRS). So you can change your code like so:

```python
dem_wgs = py3dep.get_map('DEM', utm_bounds, resolution=1, geo_crs=crs)
```

By default, `get_map` returns the requested data in 4326 so you don't have to pass `crs=4326` to `gep_map`.

**Comment by brentwilder** [comment]
Hi @cheginit , I removed the SQLite cache file and adjusted my code to have geo_crs=crs. I ran it just now after the  message from 3DEP, however, I am still seeing the 60 meter edge artifacts. 

#### On first glance of the DEM, you would think it looks OK, 
![image](https://user-images.githubusercontent.com/56372982/181388397-a5b44cd8-c317-4300-a407-596c6f6358c1.png)

#### However, when you zoom into one or two tiles you can see the edges,
![image](https://user-images.githubusercontent.com/56372982/181388714-55430f37-1f31-4b45-8dca-37b60ee6a0a9.png)

#### Then, when this is differenced with our snow dem that is continuous/seamless, these edges show up even more,
![image](https://user-images.githubusercontent.com/56372982/181388924-ffadd6f7-13cb-4840-8772-f05b955c2d66.png)

Are the USGS 3DEP 1m DEMs not seamless?

**Comment by cheginit** [comment]
Thanks for the detailed explanation. Can you give me the bounding box for this region?

**Comment by brentwilder** [comment]
Sure, it's roughly ...

Top left [43.96255,-115.68694]

Bottom Right [43.89730,-115.63931]

(EPSG 4326)

**Comment by cheginit** [comment]
I figured out why when I plot it with `xarray` and set the extent to a small region, it doesn't show these artifacts. I am guessing that your plots are done with a GIS app like QGIS and its default resampling method when you zoom in is nearest neighbor whereas `xarray` smooths it out.

Regardless, I will pass this on to the 3DEP team and get back to you as soon as I hear back from them.

**Comment by brentwilder** [comment]
Hmm.. I don't think that's it. I've tried with bilinear interpolation and I get the same result. Are you sure it's not there? It is very slight difference and really only shows it self when concentrated on the edges. I'm away from computer for the day but I'll try it with xarray when I get the chance. Thank you for your help on this!

**Comment by cheginit** [comment]
I see. Maybe where I zoomed it wasn't on the artifact line. Can you also check if before reprojecting the dataarray this issue exists? In you code, before saving it as `tif`, you're reprojecting `dem_utm`.

**Comment by brentwilder** [comment]
That was it! rioxarray defaults to nearest neighbor which was causing issues at 1m spatial resolution. I added `dem_utm = dem_wgs.rio.reproject(crs, resampling=Resampling.bilinear)` which yielded slightly better results. There are still some minor streaks from the resampling.

However, this becomes less of a py3dep issue and more of a request for added functionality.. In my opinion it would make sense if the users were able to specify __UTM__ as output, especially considering USGS 3DEP 1 meter data for CONUS are projected to UTM by default. Would something like this be in the realm of possibility for py3dep?

**Comment by cheginit** [comment]
Great, glad the issue is resolved! By "UTM as output" do you mean specifying the CRS of the 3DEP service to UTM?

**Comment by brentwilder** [comment]
Exactly. I see on the documentation that it is not currently supported. For example for my project I would want to specify the output CRS as EPSG:32611

**Comment by cheginit** [comment]
This is a limitation of the 3DEP service not `py3dep`. You can find the service specifications [here](https://elevation.nationalmap.gov/arcgis/services/3DEPElevation/ImageServer/WMSServer?request=GetCapabilities&service=WMS). If you scroll down a bit you can find the supported CRS's. You can pass any of those supported CRSs to `crs` argument of `get_map`.

In any case, I agree that reprojection can be tricky for raster data and should be avoided as much as possible. For DEM, bilinear or cubic linear should work fine though.

**Comment by brentwilder** [comment]
Ah okay got it. Well thanks so much Taher for this back and forth. This was really helpful!

**Comment by cheginit** [comment]
Sure, glad it was helpful!
